"""LeaderboardGenerator — produces HTML and Markdown leaderboards."""

from __future__ import annotations
from typing import Dict, List, Optional
from pathlib import Path


class LeaderboardGenerator:
    """Generate leaderboard in Markdown and HTML formats."""

    def __init__(self, output_dir: str = ".lyme/arena"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_markdown(self, summary: dict, output_path: Optional[str] = None) -> str:
        rankings = summary.get("rankings", [])
        lines = []
        lines.append("# Lyme Benchmark Arena — Leaderboard")
        lines.append("")
        lines.append(f"**Winner**: {summary.get('winner', 'N/A')} "
                     f"({summary.get('winner_score', 0):.4f})")
        lines.append(f"**Tools compared**: {summary.get('tool_count', 0)}")
        lines.append("")
        lines.append("## Rankings")
        lines.append("")
        lines.append("| Rank | Tool | Final Score | Correctness | Test Pass | Time Eff. | Cost Eff. | Autonomy |")
        lines.append("|------|------|-------------|-------------|-----------|-----------|-----------|----------|")

        for entry in rankings:
            dims = entry.get("dimensions", {})
            lines.append(
                f"| {entry['rank']} | {entry['tool']} | {entry['final_score']:.4f} | "
                f"{dims.get('correctness', 0):.3f} | {dims.get('test_pass_rate', 0):.3f} | "
                f"{dims.get('time_efficiency', 0):.3f} | {dims.get('cost_efficiency', 0):.3f} | "
                f"{dims.get('autonomy', 0):.3f} |"
            )

        lines.append("")
        lines.append("## Scoring Dimensions")
        lines.append("")
        lines.append("| Dimension | Weight | Description |")
        lines.append("|-----------|--------|-------------|")
        lines.append("| Correctness | 30% | Fraction of acceptance criteria met |")
        lines.append("| Test Pass Rate | 25% | Fraction of tests passing |")
        lines.append("| Time Efficiency | 10% | Faster is better (normalized) |")
        lines.append("| Cost Efficiency | 10% | Lower token cost is better |")
        lines.append("| Files Efficiency | 5% | Fewer files touched is better |")
        lines.append("| Rollback Avoidance | 5% | Fewer rollbacks is better |")
        lines.append("| Autonomy | 15% | Less human intervention needed |")
        lines.append("")
        lines.append("---")
        lines.append("*Generated by Lyme Benchmark Arena*")

        md = "\n".join(lines)
        if output_path:
            Path(output_path).write_text(md)
        else:
            path = self.output_dir / "LEADERBOARD.md"
            path.write_text(md)
        return md

    def generate_html(self, summary: dict, output_path: Optional[str] = None) -> str:
        rankings = summary.get("rankings", [])
        rows = ""
        for entry in rankings:
            dims = entry.get("dimensions", {})
            pct = max(min(entry['final_score'] * 100, 100), 0)
            bar_color = "#22c55e" if pct > 70 else ("#eab308" if pct > 40 else "#ef4444")
            rows += f"""
            <tr>
                <td class="rank">#{entry['rank']}</td>
                <td class="tool-name">{entry['tool']}</td>
                <td class="score">
                    <div class="score-bar">
                        <div class="bar-fill" style="width:{pct}%;background:{bar_color}"></div>
                        <span class="score-label">{entry['final_score']:.4f}</span>
                    </div>
                </td>
                <td>{dims.get('correctness', 0):.3f}</td>
                <td>{dims.get('test_pass_rate', 0):.3f}</td>
                <td>{dims.get('time_efficiency', 0):.3f}</td>
                <td>{dims.get('cost_efficiency', 0):.3f}</td>
                <td>{dims.get('autonomy', 0):.3f}</td>
            </tr>"""

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Lyme Benchmark Arena — Leaderboard</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; padding: 40px; }}
.container {{ max-width: 1000px; margin: 0 auto; }}
h1 {{ font-size: 2rem; font-weight: 700; margin-bottom: 8px; color: #f8fafc; }}
.subtitle {{ color: #94a3b8; margin-bottom: 32px; }}
.winner {{ display: inline-block; background: #1e293b; border: 1px solid #334155; border-radius: 8px; padding: 16px 24px; margin-bottom: 32px; }}
.winner-label {{ font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; }}
.winner-name {{ font-size: 1.5rem; font-weight: 600; color: #22c55e; }}
.winner-score {{ font-size: 1rem; color: #94a3b8; }}
table {{ width: 100%; border-collapse: collapse; background: #1e293b; border-radius: 8px; overflow: hidden; }}
th {{ background: #334155; padding: 12px 16px; text-align: left; font-weight: 600; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; color: #94a3b8; }}
td {{ padding: 14px 16px; border-bottom: 1px solid #1e293b; }}
tr:last-child td {{ border-bottom: none; }}
.rank {{ font-weight: 700; font-size: 1.1rem; color: #64748b; }}
.tool-name {{ font-weight: 600; }}
.score {{ min-width: 180px; }}
.score-bar {{ position: relative; height: 24px; background: #0f172a; border-radius: 4px; overflow: hidden; }}
.bar-fill {{ height: 100%; border-radius: 4px; transition: width 0.5s ease; }}
.score-label {{ position: absolute; top: 50%; left: 8px; transform: translateY(-50%); font-size: 0.8rem; font-weight: 600; color: #fff; text-shadow: 0 1px 2px rgba(0,0,0,0.5); }}
.dimensions {{ margin-top: 48px; }}
.dimensions h2 {{ font-size: 1.25rem; margin-bottom: 16px; color: #f8fafc; }}
.dim-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 16px; }}
.dim-card {{ background: #1e293b; border: 1px solid #334155; border-radius: 8px; padding: 16px; }}
.dim-name {{ font-weight: 600; color: #e2e8f0; }}
.dim-weight {{ color: #64748b; font-size: 0.875rem; }}
.dim-desc {{ color: #94a3b8; font-size: 0.8rem; margin-top: 4px; }}
.footer {{ margin-top: 48px; padding-top: 16px; border-top: 1px solid #334155; color: #64748b; font-size: 0.8rem; }}
</style>
</head>
<body>
<div class="container">
<h1>🏆 Lyme Benchmark Arena</h1>
<p class="subtitle">Comparing coding agents on identical tasks — normalized scoring across 7 dimensions</p>
<div class="winner">
    <div class="winner-label">Current Leader</div>
    <div class="winner-name">{summary.get('winner', 'N/A')}</div>
    <div class="winner-score">Final Score: {summary.get('winner_score', 0):.4f}</div>
</div>
<table>
<thead>
<tr><th>Rank</th><th>Tool</th><th>Final Score</th><th>Correctness</th><th>Test Pass</th><th>Time Eff.</th><th>Cost Eff.</th><th>Autonomy</th></tr>
</thead>
<tbody>{rows}</tbody>
</table>
<div class="dimensions">
<h2>Scoring Dimensions</h2>
<div class="dim-grid">
    <div class="dim-card"><div class="dim-name">Correctness</div><div class="dim-weight">Weight: 30%</div><div class="dim-desc">Fraction of acceptance criteria met</div></div>
    <div class="dim-card"><div class="dim-name">Test Pass Rate</div><div class="dim-weight">Weight: 25%</div><div class="dim-desc">Fraction of tests passing after change</div></div>
    <div class="dim-card"><div class="dim-name">Time Efficiency</div><div class="dim-weight">Weight: 10%</div><div class="dim-desc">Normalized execution speed</div></div>
    <div class="dim-card"><div class="dim-name">Cost Efficiency</div><div class="dim-weight">Weight: 10%</div><div class="dim-desc">Lower token cost is better</div></div>
    <div class="dim-card"><div class="dim-name">Files Efficiency</div><div class="dim-weight">Weight: 5%</div><div class="dim-desc">Fewer files touched is better</div></div>
    <div class="dim-card"><div class="dim-name">Rollback Avoidance</div><div class="dim-weight">Weight: 5%</div><div class="dim-desc">Fewer rollbacks is better</div></div>
    <div class="dim-card"><div class="dim-name">Autonomy</div><div class="dim-weight">Weight: 15%</div><div class="dim-desc">Less human intervention needed</div></div>
</div>
</div>
<div class="footer">Generated by Lyme Benchmark Arena — {Path(output_path).name if output_path else 'leaderboard.html'}</div>
</div>
</body>
</html>"""
        if output_path:
            Path(output_path).write_text(html)
        else:
            path = self.output_dir / "leaderboard.html"
            path.write_text(html)
        return html
