#!/usr/bin/env python3
"""Phase 9 — Agentic Model Behavior (Weeks 53-59).

Week 53: Action Grammar — structured parseable actions
Week 54: ReAct-Style Coding Traces — observe→decide→act→inspect→stop
Week 55: Tool Feedback Conditioning — use search/file/test results
Week 56: Stop Condition Training — stop when tests pass, insufficient evidence, etc.
Week 57: Planning-to-Patch Alignment — plan matches final patch
Week 59: Agentic Eval Suite

All data generated by this script.
"""

import json
import random
from pathlib import Path
from datetime import datetime, timezone
from collections import defaultdict

random.seed(53)

AGENT_DIR = Path("datasets/agentic")
AGENT_DIR.mkdir(parents=True, exist_ok=True)
REPORT_DIR = Path("lyme-output/phase9")
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# ── Week 53: Action Grammar ─────────────────────────────────────────────────

ACTION_TASKS = [
    {
        "instruction": "Find the bug causing IndexError in get_last()",
        "actions": [
            ("SEARCH", '{"query": "def get_last", "path": "src/"}', 'Found in src/utils.py:1'),
            ("READ", '{"path": "src/utils.py"}', 'def get_last(items):\n    if not items:\n        return None\n    return items[len(items)]'),
            ("PATCH", '{"file": "src/utils.py", "old": "return items[len(items)]", "new": "return items[len(items) - 1]"}', 'Patched'),
            ("RUN_TESTS", '{"command": "pytest"}', 'PASSED: 5 passed'),
            ("STOP", '{"reason": "tests_passed"}', ''),
        ]
    },
    {
        "instruction": "Fix the SQL injection vulnerability in get_user()",
        "actions": [
            ("SEARCH", '{"query": "def get_user", "path": "src/db.py"}', 'Found in src/db.py:5'),
            ("READ", '{"path": "src/db.py"}', "def get_user(username):\n    query = 'SELECT...'"),
            ("PATCH", '{"file": "src/db.py", "old": "f\\"SELECT...", "new": "SELECT * FROM users WHERE name = ?"}', 'Patched'),
            ("VERIFY", '{"check": "sql_injection_attempt"}', 'Blocked safely'),
            ("STOP", '{"reason": "verification_passed"}', ''),
        ]
    },
    {
        "instruction": "Understand the project architecture",
        "actions": [
            ("LIST_DIR", '{"path": "."}', 'src/, tests/, config/, docs/'),
            ("READ", '{"path": "pyproject.toml"}', 'name = "my-app"\ndependencies = ["fastapi", "sqlalchemy"]'),
            ("STOP", '{"reason": "sufficient_evidence"}', ''),
        ]
    },
    {
        "instruction": "What framework does this project use?",
        "actions": [
            ("READ", '{"path": "pyproject.toml"}', 'dependencies = ["fastapi", "uvicorn"]'),
            ("STOP", '{"reason": "found_answer"}', ''),
        ]
    },
]

def gen_action_grammar():
    examples = []
    for task in ACTION_TASKS:
        for _ in range(30):
            action_seq = []
            for action, args, result in task["actions"]:
                action_seq.append({
                    "tool_name": action,
                    "arguments": json.loads(args) if args else {},
                    "result_summary": result[:200],
                    "success": True,
                    "latency_ms": random.randint(100, 3000),
                })
            target = "\n".join(f"<{action} args={args}>{result[:40]}..." for action, args, result in task["actions"])
            examples.append({
                "id": f"action-grammar-{random.randint(1000,9999)}",
                "modality": "tool_use",
                "created": datetime.now(timezone.utc).isoformat(),
                "source": "synthetic",
                "difficulty": "medium",
                "instruction": task["instruction"],
                "repo_context": {"repo_name": "agent-project", "language": "Python"},
                "retrieved_files": [{"file_path": "src/main.py", "role": "source", "content_preview": "", "lines": 0, "relevance_score": 1.0}],
                "tool_outputs": action_seq,
                "target_output": target,
                "metadata": {"agentic_training": "action_grammar", "tag": "week53", "num_actions": len(task["actions"])},
            })
    return examples

# ── Week 54: ReAct-Style Traces ────────────────────────────────────────────

REACT_TASKS = [
    {
        "observations": [
            "Observation: The test test_average_empty is failing with ZeroDivisionError",
            "Action: READ src/calculator.py → 'def average(nums): return sum(nums) / len(nums)'",
            "Observation: The function has no guard for empty list",
            "Action: PATCH src/calculator.py → added 'if not nums: return 0.0'",
            "Observation: Patch applied successfully",
            "Action: RUN_TESTS pytest → 'PASSED: all 3 tests pass'",
            "Observation: All tests pass",
            "Action: STOP",
        ],
        "task": "Fix the ZeroDivisionError in average() when nums is empty.",
    },
    {
        "observations": [
            "Observation: The endpoint returns 500 on empty input",
            "Action: SEARCH for 'average' → found in src/calculator.py:1",
            "Observation: average() divides by len(nums) without null check",
            "Action: READ tests/test_calculator.py → 'def test_average_empty(): fails'",
            "Observation: Test expects average([]) == 0.0",
            "Action: PATCH src/calculator.py → add null check",
            "Observation: Patch applied",
            "Action: RUN_TESTS → 'PASSED'",
            "Observation: Tests pass",
            "Action: STOP reason=tests_passed",
        ],
        "task": "Fix the 500 error when users submit empty data to the API.",
    },
]

def gen_react_traces():
    examples = []
    for task in REACT_TASKS:
        for _ in range(30):
            target = "\n".join(task["observations"])
            examples.append({
                "id": f"react-trace-{random.randint(1000,9999)}",
                "modality": "tool_use",
                "created": datetime.now(timezone.utc).isoformat(),
                "source": "synthetic",
                "difficulty": "medium",
                "instruction": task["task"],
                "repo_context": {"repo_name": "react-project", "language": "Python"},
                "retrieved_files": [{"file_path": "src/main.py", "role": "source", "content_preview": "", "lines": 0, "relevance_score": 1.0}],
                "tool_outputs": [{"tool_name": "react_step", "arguments": {"step": i}, "result_summary": obs[:100], "success": True, "latency_ms": 500} for i, obs in enumerate(task["observations"])],
                "target_output": target,
                "metadata": {"agentic_training": "react_trace", "tag": "week54", "num_steps": len(task["observations"])},
            })
    return examples

# ── Week 55: Tool Feedback Conditioning ────────────────────────────────────

FEEDBACK_TASKS = [
    {
        "instruction": "Fix the TestFailure. Tests failed. Search results show: 'ERROR in src/calculator.py:2 division by zero'",
        "context": "Test failure: ZeroDivisionError\nSearch result: src/calculator.py, line 2, average()",
        "target": "Read src/calculator.py to see the division, then patch with null check.",
    },
    {
        "instruction": "PatchError: The diff did not apply. Files may have changed since read.",
        "context": "PatchError at src/config.py: old string not found. File content may differ.",
        "target": "Re-read the file first to get current content, then regenerate the patch.",
    },
    {
        "instruction": "CriticFeedback: This patch is risky. It modifies 5 unrelated files.",
        "context": "Critic says: overbroad edit, modifies files unrelated to the bug fix.",
        "target": "Reduce the patch to only the minimal changes needed for the bug fix.",
    },
    {
        "instruction": "Search returned no results for 'SECRET_KEY'. The key may use a different name.",
        "context": "No matches for SECRET_KEY. Try searching for 'secret' or 'key' or check config files.",
        "target": "Try broader search for 'secret' or list config directory to find the right file.",
    },
]

def gen_tool_feedback():
    examples = []
    for task in FEEDBACK_TASKS:
        for _ in range(30):
            examples.append({
                "id": f"feedback-{random.randint(1000,9999)}",
                "modality": "tool_use",
                "created": datetime.now(timezone.utc).isoformat(),
                "source": "synthetic",
                "difficulty": "medium",
                "instruction": task["instruction"],
                "repo_context": {"repo_name": "feedback-project", "language": "Python"},
                "retrieved_files": [{"file_path": "src/main.py", "role": "source", "content_preview": task["context"][:200]}],
                "tool_outputs": [{"tool_name": "feedback", "arguments": {"type": "error"}, "result_summary": task["context"][:200], "success": False, "latency_ms": 200}],
                "target_output": task["target"],
                "metadata": {"agentic_training": "tool_feedback", "tag": "week55"},
            })
    return examples

# ── Week 56: Stop Conditions ──────────────────────────────────────────────

STOP_TASKS = [
    {
        "instruction": "Run tests after patching to verify the fix.",
        "condition": "STOP reason=tests_passed — all 5 tests pass after patch",
        "target": "STOP",
    },
    {
        "instruction": "You've searched 3 different directories and found insufficient evidence for the bug location.",
        "condition": "STOP reason=insufficient_evidence — cannot locate the bug with available context",
        "target": "STOP",
    },
    {
        "instruction": "The patch would delete the entire error handling module. This is too risky.",
        "condition": "STOP reason=unsafe_patch — patch would cause regression in error handling",
        "target": "STOP",
    },
    {
        "instruction": "The task 'Rewrite the entire application' is too broad for a single session.",
        "condition": "STOP reason=task_too_broad — task requires multi-session planning",
        "target": "STOP",
    },
    {
        "instruction": "You've attempted 5 different patches and none pass all tests.",
        "condition": "STOP reason=max_attempts_reached — 5 attempts exhausted",
        "target": "STOP",
    },
    {
        "instruction": "There is no test command defined for this project. Cannot verify the fix.",
        "condition": "STOP reason=no_test_command — no pytest.ini, tox.ini, or Makefile found",
        "target": "STOP",
    },
]

def gen_stop_conditions():
    examples = []
    for task in STOP_TASKS:
        for _ in range(25):
            examples.append({
                "id": f"stop-{random.randint(1000,9999)}",
                "modality": "tool_use",
                "created": datetime.now(timezone.utc).isoformat(),
                "source": "synthetic",
                "difficulty": "medium",
                "instruction": task["instruction"],
                "repo_context": {"repo_name": "stop-project", "language": "Python"},
                "retrieved_files": [{"file_path": "src/main.py", "role": "source", "content_preview": task["condition"][:200]}],
                "tool_outputs": [],
                "target_output": task["target"],
                "metadata": {"agentic_training": "stop_condition", "tag": "week56", "condition": task["condition"].split("—")[0].strip()},
            })
    return examples

# ── Week 57: Plan-Patch Alignment ──────────────────────────────────────────

PLAN_PATCH_TASKS = [
    {
        "instruction": "Fix the ZeroDivisionError in average()",
        "plan": "Plan: 1. Add guard clause 'if not nums: return 0.0' in src/calculator.py 2. Keep existing return 3. Add test for empty list",
        "patch": "--- a/src/calculator.py\n+++ b/src/calculator.py\n@@ -1,2 +1,5 @@\n def average(nums):\n+    if not nums:\n+        return 0.0\n     return sum(nums) / len(nums)",
        "files": ["src/calculator.py"],
        "aligned": True,
    },
    {
        "instruction": "Fix the wrong test assertion in test_calc.py",
        "plan": "Plan: 1. Change expected value from 10 to 15 in tests/test_calc.py",
        "patch": "--- a/tests/test_calc.py\n+++ b/tests/test_calc.py\n@@ -2,2 +2,2 @@\n def test_multiply():\n-    assert multiply(3, 5) == 10\n+    assert multiply(3, 5) == 15",
        "files": ["tests/test_calc.py"],
        "aligned": True,
    },
    {
        "instruction": "Fix the bug",
        "plan": "Plan: 1. Fix src/config.py 2. Update tests 3. Add logging 4. Refactor everything",
        "patch": "--- a/src/unrelated.py\n+++ b/src/unrelated.py\n@@ -1 +1 @@\n-old\n+new",
        "files": ["src/unrelated.py"],
        "aligned": False,
    },
]

def gen_plan_patch_alignment():
    examples = []
    for task in PLAN_PATCH_TASKS:
        for _ in range(30):
            examples.append({
                "id": f"plan-patch-{random.randint(1000,9999)}",
                "modality": "patch_planning",
                "created": datetime.now(timezone.utc).isoformat(),
                "source": "synthetic",
                "difficulty": "hard",
                "instruction": f"{task['instruction']}\n\nPlan:\n{task['plan']}",
                "repo_context": {"repo_name": "alignment-project", "language": "Python"},
                "retrieved_files": [{"file_path": f, "role": "source", "content_preview": "", "lines": 0, "relevance_score": 1.0} for f in task["files"]],
                "tool_outputs": [],
                "target_output": task["patch"],
                "metadata": {"agentic_training": "plan_patch_alignment", "tag": "week57", "aligned": task["aligned"]},
            })
    return examples

# ── Week 58: Agent Loop Runtime ───────────────────────────────────────────

def build_runtime():
    return {
        "name": "lyme-agent-loop-v2",
        "version": "2.0",
        "description": "Parses model output as structured actions, executes tools, returns observations.",
        "actions": {
            "SEARCH": {"description": "Search codebase for pattern", "args": {"query": "str", "path": "str (optional)"}},
            "READ": {"description": "Read file contents", "args": {"path": "str"}},
            "PATCH": {"description": "Apply edit to file", "args": {"file": "str", "old": "str", "new": "str"}},
            "RUN_TESTS": {"description": "Run test command", "args": {"command": "str"}},
            "VERIFY": {"description": "Run verification check", "args": {"check": "str"}},
            "LIST_DIR": {"description": "List directory contents", "args": {"path": "str"}},
            "STOP": {"description": "Stop execution", "args": {"reason": "str"}},
        },
        "safety": {
            "max_steps": 20,
            "max_patch_size": 1000,
            "allowed_dirs": ["src/", "tests/", "config/"],
            "forbidden_patterns": ["rm -rf", "DROP TABLE"],
        },
    }

# ── Week 59: Agentic Eval Suite ──────────────────────────────────────────

EVAL_TASKS = [
    {
        "id": "agent-eval-001",
        "task": "Fix the failing test: test_average_empty fails with ZeroDivisionError",
        "files": {"src/calculator.py": "def average(nums): return sum(nums) / len(nums)",
                  "tests/test_calc.py": "def test_average_empty(): assert average([]) == 0.0"},
        "expected_patch": "--- a/src/calculator.py\n+++ b/src/calculator.py\n@@ -1 +1,4 @@\n+def average(nums):\n+    if not nums:\n+        return 0.0\n     return sum(nums) / len(nums)",
        "success_criteria": "tests pass",
    },
    {
        "id": "agent-eval-002",
        "task": "Find the bug: get_last([1,2,3]) raises IndexError",
        "files": {"src/utils.py": "def get_last(items):\n    if not items:\n        return None\n    return items[len(items)]"},
        "expected_answer": "Off-by-one error in src/utils.py: return items[len(items) - 1]",
        "success_criteria": "correct localization",
    },
    {
        "id": "agent-eval-003",
        "task": "Add a --name CLI option to the greet command",
        "files": {"src/cli.py": "import click\n\n@click.command()\ndef greet():\n    click.echo('Hello!')",
                  "tests/test_cli.py": "from click.testing import CliRunner\nfrom src.cli import greet\n\ndef test_greet():\n    runner = CliRunner()\n    result = runner.invoke(greet, [])\n    assert result.exit_code == 0"},
        "expected_patch": "--- a/src/cli.py\n+++ b/src/cli.py\n@@ -1,4 +1,5 @@\n import click\n \n @click.command()\n-def greet():\n-    click.echo('Hello!')\n+@click.option('--name', default='World', help='Who to greet')\n+def greet(name):\n+    click.echo(f'Hello, {name}!')",
        "success_criteria": "option works",
    },
    {
        "id": "agent-eval-004",
        "task": "Update config key from SECRET_KEY to APP_SECRET in all files",
        "files": {"config/settings.py": "SECRET_KEY = 'dev'",
                  "src/auth.py": "from config import SECRET_KEY",
                  "tests/test_auth.py": "from config import SECRET_KEY"},
        "expected_answer": "Multi-file rename across 3 files",
        "success_criteria": "all references updated",
    },
]

def build_eval_suite():
    suite = {
        "name": "Lyme Agentic Eval Suite v1",
        "description": "Evaluates agentic coding behavior: tool use, planning, patching, verification",
        "scoring": {
            "task_success": {"weight": 40, "description": "Task completes successfully"},
            "action_validity": {"weight": 20, "description": "All actions are parseable"},
            "tool_efficiency": {"weight": 15, "description": "Minimal unnecessary tool calls"},
            "patch_validity": {"weight": 15, "description": "Patch applies and is well-formed"},
            "final_verification": {"weight": 10, "description": "Verification step passes"},
        },
        "tasks": EVAL_TASKS,
    }
    return suite

def main():
    print("=" * 72)
    print("  Phase 9 — Agentic Model Behavior (Weeks 53-59)")
    print("=" * 72)

    all_data = {}

    # Week 53
    w53 = gen_action_grammar()
    all_data["week53_action_grammar"] = w53
    print(f"\n  Week 53 — Action Grammar: {len(w53)} examples")

    # Week 54
    w54 = gen_react_traces()
    all_data["week54_react_traces"] = w54
    print(f"  Week 54 — ReAct Traces: {len(w54)} examples")

    # Week 55
    w55 = gen_tool_feedback()
    all_data["week55_tool_feedback"] = w55
    print(f"  Week 55 — Tool Feedback: {len(w55)} examples")

    # Week 56
    w56 = gen_stop_conditions()
    all_data["week56_stop_conditions"] = w56
    print(f"  Week 56 — Stop Conditions: {len(w56)} examples")

    # Week 57
    w57 = gen_plan_patch_alignment()
    all_data["week57_plan_patch"] = w57
    print(f"  Week 57 — Plan-Patch Alignment: {len(w57)} examples")

    # Save all data
    for key, examples in all_data.items():
        week_dir = AGENT_DIR / key
        week_dir.mkdir(parents=True, exist_ok=True)
        random.shuffle(examples)
        n = len(examples)
        train = examples[:int(n*0.7)]
        val = examples[int(n*0.7):int(n*0.85)]
        test = examples[int(n*0.85):]
        for split_name, split_exs in [("train", train), ("val", val), ("test", test)]:
            split_dir = week_dir / split_name
            split_dir.mkdir(parents=True, exist_ok=True)
            with open(split_dir / "combined.jsonl", "w") as f:
                for ex in split_exs:
                    f.write(json.dumps(ex) + "\n")
        print(f"    Saved: train={len(train)} val={len(val)} test={len(test)}")

    # Week 58: Runtime config
    runtime = build_runtime()
    runtime_path = AGENT_DIR / "agent_runtime_v2.json"
    runtime_path.write_text(json.dumps(runtime, indent=2))
    print(f"\n  Week 58 — Agent Runtime v2 config: {runtime_path}")

    # Week 59: Eval suite
    eval_suite = build_eval_suite()
    eval_path = AGENT_DIR / "agentic_eval_suite.json"
    eval_path.write_text(json.dumps(eval_suite, indent=2))
    print(f"  Week 59 — Agentic Eval Suite: {eval_path} ({len(EVAL_TASKS)} tasks)")

    total = sum(len(v) for v in all_data.values())
    print(f"\n  Total Phase 9 examples: {total}")
    print("=" * 72)

if __name__ == "__main__":
    main()
