from __future__ import annotations

import json
from typing import Any, Dict, List, Optional, Set

from .causal_graph import CausalGraph, CausalNode, CausalEdge, CausalRelationType


class CausalGraphRenderer:
    def __init__(self, graph: CausalGraph):
        self.graph = graph

    def to_graphviz(self, include_confidence: bool = True) -> str:
        lines = ["digraph CausalGraph {"]
        lines.append("  rankdir=LR;")
        lines.append("  node [shape=box, style=rounded, fontname=monospace];")
        lines.append("  edge [fontname=monospace, fontsize=10];")

        for node in self.graph._nodes.values():
            color = self._risk_color(node.risk_score)
            label = f"{node.name}" + (f"\\n(risk={node.risk_score:.2f})" if include_confidence else "")
            lines.append(f'  "{node.id}" [label="{label}", fillcolor="{color}", style="filled,rounded"];')

        for edge in self.graph._edges.values():
            color = self._confidence_color(edge.confidence)
            style = "dashed" if edge.confidence < 0.5 else "solid"
            label = f"{edge.relation_type.value}" + (f"\\n({edge.confidence:.2f})" if include_confidence else "")
            lines.append(
                f'  "{edge.source_id}" -> "{edge.target_id}" '
                f'[label="{label}", color="{color}", style="{style}", '
                f'penwidth={max(0.5, edge.weight * 3)}];'
            )

        lines.append("}")
        return "\n".join(lines)

    def to_mermaid(self) -> str:
        lines = ["```mermaid", "graph LR;"]
        style_lines = []

        for node in self.graph._nodes.values():
            color = self._risk_color_hex(node.risk_score)
            node_id = node.id.replace("-", "_")
            display_name = node.name.split("/")[-1] if "/" in node.name else node.name
            lines.append(f"    {node_id}[\"{display_name}\"]")
            style_lines.append(f"    style {node_id} fill:{color},stroke:#333,color:#fff;")

        for edge in self.graph._edges.values():
            src = edge.source_id.replace("-", "_")
            tgt = edge.target_id.replace("-", "_")
            label = f"{edge.relation_type.value[:3]}"
            lines.append(f"    {src}-->{tgt}|{label}|;")

        lines.extend(style_lines)
        lines.append("```")
        return "\n".join(lines)

    def to_html(self, title: str = "Causal Software Graph") -> str:
        nodes_json = json.dumps([n.to_dict() for n in self.graph._nodes.values()], indent=2)
        edges_json = json.dumps([e.to_dict() for e in self.graph._edges.values()], indent=2)

        return f"""<!DOCTYPE html>
<html>
<head>
<title>{title}</title>
<style>
  body {{ font-family: monospace; margin: 20px; background: #0d1117; color: #c9d1d9; }}
  h1 {{ color: #58a6ff; }}
  .stats {{ display: flex; gap: 20px; margin: 10px 0; }}
  .stat-box {{ background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 12px; flex: 1; }}
  .stat-box h3 {{ margin: 0 0 5px 0; color: #8b949e; font-size: 12px; text-transform: uppercase; }}
  .stat-box .value {{ font-size: 24px; font-weight: bold; }}
  .graph-container {{ margin: 20px 0; }}
  .node-list {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 8px; }}
  .node-card {{ background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 8px 12px; }}
  .node-card .name {{ color: #58a6ff; }}
  .node-card .risk {{ float: right; }}
  .risk-high {{ color: #f85149; }}
  .risk-med {{ color: #d29922; }}
  .risk-low {{ color: #3fb950; }}
  .edge-table {{ width: 100%; border-collapse: collapse; }}
  .edge-table th, .edge-table td {{ text-align: left; padding: 6px 12px; border-bottom: 1px solid #21262d; }}
  .edge-table th {{ color: #8b949e; }}
  svg {{ background: #0d1117; }}
</style>
</head>
<body>
<h1>{title}</h1>
<div class="stats">
  <div class="stat-box"><h3>Nodes</h3><div class="value" style="color:#58a6ff">{len(self.graph._nodes)}</div></div>
  <div class="stat-box"><h3>Edges</h3><div class="value" style="color:#a5d6ff">{len(self.graph._edges)}</div></div>
  <div class="stat-box"><h3>Relation Types</h3><div class="value" style="color:#7ee787">{len(self.graph._type_index)}</div></div>
  <div class="stat-box"><h3>High Risk</h3><div class="value" style="color:#f85149">{sum(1 for n in self.graph._nodes.values() if n.risk_score >= 0.7)}</div></div>
</div>

<h2>Nodes by Risk</h2>
<div class="node-list">
{self._html_node_cards()}
</div>

<h2>Edges</h2>
<table class="edge-table">
<tr><th>Source</th><th>Target</th><th>Type</th><th>Confidence</th><th>Weight</th></tr>
{self._html_edge_rows()}
</table>

<h2>Edge Type Distribution</h2>
<div class="stats">
{self._html_type_distribution()}
</div>

<p><small>Generated by Lyme Causal Graph Engine</small></p>
</body>
</html>"""

    def to_d3_json(self) -> Dict[str, Any]:
        return {
            "nodes": [
                {
                    "id": n.id,
                    "name": n.name,
                    "type": n.node_type.value if hasattr(n.node_type, 'value') else str(n.node_type),
                    "subsystem": n.subsystem,
                    "risk_score": n.risk_score,
                    "import_count": n.import_count,
                    "dependents_count": n.dependents_count,
                }
                for n in self.graph._nodes.values()
            ],
            "links": [
                {
                    "source": e.source_id,
                    "target": e.target_id,
                    "type": e.relation_type.value if hasattr(e.relation_type, 'value') else str(e.relation_type),
                    "confidence": e.confidence,
                    "weight": e.weight,
                }
                for e in self.graph._edges.values()
            ],
        }

    def _html_node_cards(self) -> str:
        sorted_nodes = sorted(
            self.graph._nodes.values(),
            key=lambda n: n.risk_score,
            reverse=True,
        )[:50]
        cards = []
        for n in sorted_nodes:
            risk_class = "risk-high" if n.risk_score >= 0.7 else "risk-med" if n.risk_score >= 0.4 else "risk-low"
            short_name = n.name.split("/")[-1] if "/" in n.name else n.name
            cards.append(
                f'<div class="node-card">'
                f'<span class="name">{short_name}</span>'
                f'<span class="risk {risk_class}">{n.risk_score:.2f}</span>'
                f'<br><small style="color:#8b949e">{n.file_path} | {n.node_type}</small>'
                f'</div>'
            )
        return "\n".join(cards)

    def _html_edge_rows(self) -> str:
        sorted_edges = sorted(
            self.graph._edges.values(),
            key=lambda e: e.confidence,
            reverse=True,
        )[:50]
        rows = []
        for e in sorted_edges:
            src = self.graph.get_node(e.source_id)
            tgt = self.graph.get_node(e.target_id)
            src_name = src.name.split("/")[-1] if src and "/" in src.name else (src.name if src else e.source_id)
            tgt_name = tgt.name.split("/")[-1] if tgt and "/" in tgt.name else (tgt.name if tgt else e.target_id)
            rows.append(
                f"<tr><td>{src_name}</td><td>{tgt_name}</td>"
                f"<td>{e.relation_type.value}</td>"
                f"<td>{e.confidence:.2f}</td>"
                f"<td>{e.weight:.2f}</td></tr>"
            )
        return "\n".join(rows)

    def _html_type_distribution(self) -> str:
        boxes = []
        for rtype, edge_ids in sorted(self.graph._type_index.items(), key=lambda x: -len(x[1])):
            label = rtype.value if hasattr(rtype, 'value') else str(rtype)
            boxes.append(
                f'<div class="stat-box"><h3>{label}</h3>'
                f'<div class="value">{len(edge_ids)}</div></div>'
            )
        return "\n".join(boxes[:8])

    def _risk_color(self, score: float) -> str:
        if score >= 0.7:
            return "#f85149"
        elif score >= 0.4:
            return "#d29922"
        return "#3fb950"

    def _risk_color_hex(self, score: float) -> str:
        if score >= 0.7:
            return "#f85149"
        elif score >= 0.4:
            return "#d29922"
        return "#3fb950"

    def _confidence_color(self, score: float) -> str:
        if score >= 0.7:
            return "#58a6ff"
        elif score >= 0.4:
            return "#a5d6ff"
        return "#8b949e"
